# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class Treborctl < Formula
  desc "Treborctl command line tool"
  homepage "https://github.com/trebornaut/treborctl"
  version "0.3.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/trebornaut/treborctl/releases/download/v0.3.8/treborctl_0.3.8_Darwin_x86_64.zip", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "9c9a19b7671abc4d51103ce58a97d1be44708173fe6aaa1baa22e53419edc8e8"

      def install
        bin.install "treborctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/trebornaut/treborctl/releases/download/v0.3.8/treborctl_0.3.8_Darwin_arm64.zip", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "288a9e697151fb746ce75bff4d76ded42c4f3f182579fa362e7f9570f5e29862"

      def install
        bin.install "treborctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/trebornaut/treborctl/releases/download/v0.3.8/treborctl_0.3.8_Linux_x86_64.zip", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "83662cd7fae90dae06c222e8280a19ce9492bfced90cff84c727b216d66b0244"
      def install
        bin.install "treborctl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/trebornaut/treborctl/releases/download/v0.3.8/treborctl_0.3.8_Linux_arm64.zip", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "8717cee658cbf9db0a745d499f75ec873ff4357bc6485801b789f5c4eb55713b"
      def install
        bin.install "treborctl"
      end
    end
  end

  test do
    system "#{bin}/treborctl", "--version"
  end
end
